stages:
- name: test1
  steps:
  - runScriptConfig:
      image: busybox:latest
      shellScript: ls
- name: test
  steps:
  - runScriptConfig:
      image: busybox:latest
      shellScript: ls
timeout: 60
notification: {}
