stages:
- name: output
  steps:
  - runScriptConfig:
      image: busybox:latest
      shellScript: ls
  - runScriptConfig:
      image: busybox:latest
      shellScript: ip addr
    privileged: true
timeout: 60
