stages:
- name: output
  steps:
  - runScriptConfig:
      image: busybox:latest
      shellScript: ls
  - runScriptConfig:
      image: busybox:latest
      shellScript: echo "TEST TEST"
    privileged: true
timeout: 60
