stages:
- name: publish
  steps:
  - publishCatalogConfig:
      path: ${chartpath}
      catalogTemplate: test-chart
      version: latest
      gitUrl: https://github.com/bmdepesa/test-charts.git
      gitBranch: master
      gitAuthor: brandon-test
      gitEmail: brandon@rancher.com
    env:
      chartpath: ./charts-test-path
    envFrom:
    - sourceName: test-secret
      sourceKey: USERNAME
      targetKey: USERNAME
    - sourceName: test-secret
      sourceKey: PASSWORD
      targetKey: PASSWORD
branch: {}
notification: {}
