stages:
- name: Global Level
  steps:
  - applyAppConfig:
      catalogTemplate: cattle-global-data:test
      version: 0.1.0
      name: global
      targetNamespace: global
- name: Project Level
  steps:
  - applyAppConfig:
      catalogTemplate: p-9gvzt:projecttest
      version: 0.1.0
      name: project
      targetNamespace: project
branch:
  include:
  - pipeline
  exclude: