stages:
- name: publish
  steps:
  - publishCatalogConfig:
      path: ${chartpath}
      catalogTemplate: test-chart
      version: latest
      gitUrl: https://github.com/bmdepesa/test-chart
      gitBranch: master
      gitAuthor: chartpath
      gitEmail: ./charts-test-path
    envFrom:
    - sourceName: test-secret
      sourceKey: USERNAME
      targetKey: USERNAME
    - sourceName: test-secret
      sourceKey: PASSWORD
      targetKey: PASSWORD
branch: {}
notification: {}
