stages:
- name: output
  steps:
  - runScriptConfig:
      image: busybox:latest
      shellScript: |-
        ls
        sleep 5m
    privileged: true
  - runScriptConfig:
      image: busybox:latest
      shellScript: ip addr
timeout: 60
