stages:
- name: output
  steps:
  - runScriptConfig:
      image: busybox:latest
      shellScript: ls /dev/kvm
  - runScriptConfig:
      image: busybox:latest
      shellScript: ip addr
timeout: 60
